version: "3.8"

networks:
  private:
    external: true
    name: private

services:
  server-dashboard:
    image: server-dashboard:dev
    container_name: server-dashboard
    ports: 
      - "8000:8000"
    dns:
      - 10.0.0.2
      - 1.1.1.1
    volumes:
      - /volume1/docker/server-dashboard/config.yaml:/app/config.yaml
      - /volume1/docker/server-dashboard/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      private:     
        aliases:
          - server-dashboard
